-- 创建基线科目

-- 创建银行存款-微信小程序rycx科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'1001035', '银行存款-微信小程序rycx', 2, '1001', 'N', '1', 1, 'Y', sysdate, sysdate, '银行存款-微信小程序rycx', 1);
-- 银行存款-微信小程序rycx 科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'1001035001', '银行存款-微信小程序rycx', 3, '1001035', 'Y', '1', 1, 'Y', sysdate, sysdate, '银行存款-微信小程序rycx', 1);
INSERT INTO dpm.t_dpm_inner_account (ACCOUNT_NO,ACCOUNT_TITLE_NO,ACCOUNT_NAME,OPEN_DATE,BAL_DIRECTION,CURR_BAL_DIRECTION,CURRENCY_CODE,BALANCE,LAST_UPDATE_TIME) VALUES ('10010350010101','1001035001','银行存款-微信小程序rycx',sysdate,1,1,'CNY',0.0000,sysdate);

-- 创建渠道管理费-微信小程序rycx科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'1002035', '渠道管理费-微信小程序rycx', 2, '1002', 'N', '1', 1, 'Y', sysdate, sysdate, '渠道管理费-微信小程序rycx', 1);
-- 渠道管理费-微信小程序rycx 科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'1002035001', '渠道管理费-微信小程序rycx', 3, '1002035', 'Y', '1', 1, 'Y', sysdate, sysdate, '渠道管理费-微信小程序rycx', 1);
INSERT INTO dpm.t_dpm_inner_account (ACCOUNT_NO,ACCOUNT_TITLE_NO,ACCOUNT_NAME,OPEN_DATE,BAL_DIRECTION,CURR_BAL_DIRECTION,CURRENCY_CODE,BALANCE,LAST_UPDATE_TIME) VALUES ('10020350010101','1002035001','渠道管理费-微信小程序rycx',sysdate,1,1,'CNY',0.0000,sysdate);

-- 创建调拨手续费-微信小程序rycx科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'1003035', '调拨手续费-微信小程序rycx', 2, '1003', 'N', '1', 1, 'Y', sysdate, sysdate, '调拨手续费-微信小程序rycx', 1);
-- 调拨手续费-微信小程序rycx 科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'1003035001', '调拨手续费-微信小程序rycx', 3, '1003035', 'Y', '1', 1, 'Y', sysdate, sysdate, '调拨手续费-微信小程序rycx', 1);
INSERT INTO dpm.t_dpm_inner_account (ACCOUNT_NO,ACCOUNT_TITLE_NO,ACCOUNT_NAME,OPEN_DATE,BAL_DIRECTION,CURR_BAL_DIRECTION,CURRENCY_CODE,BALANCE,LAST_UPDATE_TIME) VALUES ('10030350010101','1003035001','调拨手续费-微信小程序rycx',sysdate,1,1,'CNY',0.0000,sysdate);

-- 创建银行短款-微信小程序rycx科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'1004035', '银行短款-微信小程序rycx', 2, '1004', 'N', '1', 1, 'Y', sysdate, sysdate, '银行短款-微信小程序rycx', 1);
-- 银行短款-微信小程序rycx 科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'1004035001', '银行短款-微信小程序rycx', 3, '1004035', 'Y', '1', 1, 'Y', sysdate, sysdate, '银行短款-微信小程序rycx', 1);
INSERT INTO dpm.t_dpm_inner_account (ACCOUNT_NO,ACCOUNT_TITLE_NO,ACCOUNT_NAME,OPEN_DATE,BAL_DIRECTION,CURR_BAL_DIRECTION,CURRENCY_CODE,BALANCE,LAST_UPDATE_TIME) VALUES ('10040350010101','1004035001','银行短款-微信小程序rycx',sysdate,1,1,'CNY',0.0000,sysdate);
-- 利息收入款-微信小程序rycx 科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'2003002035', '利息收入款-微信小程序rycx', 3, '2003002', 'Y', '2', 2, 'Y', sysdate, sysdate, '利息收入款-微信小程序rycx', 1);
INSERT INTO dpm.t_dpm_inner_account (ACCOUNT_NO,ACCOUNT_TITLE_NO,ACCOUNT_NAME,OPEN_DATE,BAL_DIRECTION,CURR_BAL_DIRECTION,CURRENCY_CODE,BALANCE,LAST_UPDATE_TIME) VALUES ('20030020350101','2003002035','利息收入款-微信小程序rycx',sysdate,2,2,'CNY',0.0000,sysdate);
-- 银行长款-微信小程序rycx 科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'2003003035', '银行长款-微信小程序rycx', 3, '2003003', 'Y', '2', 2, 'Y', sysdate, sysdate, '银行长款-微信小程序rycx', 1);
INSERT INTO dpm.t_dpm_inner_account (ACCOUNT_NO,ACCOUNT_TITLE_NO,ACCOUNT_NAME,OPEN_DATE,BAL_DIRECTION,CURR_BAL_DIRECTION,CURRENCY_CODE,BALANCE,LAST_UPDATE_TIME) VALUES ('20030030350101','2003003035','银行长款-微信小程序rycx',sysdate,2,2,'CNY',0.0000,sysdate);
-- 待清算-入款待清算-微信小程序rycx 科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'4001001035', '待清算-入款待清算-微信小程序rycx', 3, '4001001', 'Y', '4', 0, 'Y', sysdate, sysdate, '待清算-入款待清算-微信小程序rycx', 1);
INSERT INTO dpm.t_dpm_inner_account (ACCOUNT_NO,ACCOUNT_TITLE_NO,ACCOUNT_NAME,OPEN_DATE,BAL_DIRECTION,CURR_BAL_DIRECTION,CURRENCY_CODE,BALANCE,LAST_UPDATE_TIME) VALUES ('40010010350101','4001001035','待清算-入款待清算-微信小程序rycx',sysdate,0,1,'CNY',0.0000,sysdate);
-- 待清算-退款待清算-微信小程序rycx 科目
INSERT INTO dpm.t_act_account_titile (TITLE_SEQ_NO,TITLE_CODE, TITLE_NAME, TITLE_LEVEL, PARENT_TITLE_CODE, IS_LEAF, TYPE, BALANCE_DIRECTION, STATUS, GMT_MODIFIED, GMT_CREATE, MEMO, TITLE_RANGE) VALUES (dpm.SEQ_ACCOUNT_TITILE.nextval,'4001003035', '待清算-退款待清算-微信小程序rycx', 3, '4001003', 'Y', '4', 0, 'Y', sysdate, sysdate, '待清算-退款待清算-微信小程序rycx', 1);
INSERT INTO dpm.t_dpm_inner_account (ACCOUNT_NO,ACCOUNT_TITLE_NO,ACCOUNT_NAME,OPEN_DATE,BAL_DIRECTION,CURR_BAL_DIRECTION,CURRENCY_CODE,BALANCE,LAST_UPDATE_TIME) VALUES ('40010030350101','4001003035','待清算-退款待清算-微信小程序rycx',sysdate,0,1,'CNY',0.0000,sysdate);
